package util.extensions

val String.boolean: Boolean
	get() = toBoolean()
val String.byte: Byte
	get() = toByte()
val String.short: Short
	get() = toShort()
val String.int: Int
	get() = toInt()
val String.long: Long
	get() = toLong()
val String.float: Float
	get() = toFloat()
val String.double: Double
	get() = toDouble()
val Char.byte: Byte
	get() = toByte()
val Char.short: Short
	get() = toShort()
val Char.int: Int
	get() = toInt()
val Char.long: Long
	get() = toLong()
val Char.float: Float
	get() = toFloat()
val Char.double: Double
	get() = toDouble()
val Char.string: String
	get() = toString()
val String.string: String
	get() = toString()
val Byte.byte: Byte
	get() = toByte()
val Byte.short: Short
	get() = toShort()
val Byte.int: Int
	get() = toInt()
val Byte.long: Long
	get() = toLong()
val Byte.float: Float
	get() = toFloat()
val Byte.double: Double
	get() = toDouble()
val Byte.string: String
	get() = toString()
val Short.byte: Byte
	get() = toByte()
val Short.short: Short
	get() = toShort()
val Short.int: Int
	get() = toInt()
val Short.long: Long
	get() = toLong()
val Short.float: Float
	get() = toFloat()
val Short.double: Double
	get() = toDouble()
val Short.string: String
	get() = toString()
val Int.byte: Byte
	get() = toByte()
val Int.short: Short
	get() = toShort()
val Int.int: Int
	get() = toInt()
val Int.long: Long
	get() = toLong()
val Int.float: Float
	get() = toFloat()
val Int.double: Double
	get() = toDouble()
val Int.string: String
	get() = toString()
val Long.byte: Byte
	get() = toByte()
val Long.short: Short
	get() = toShort()
val Long.int: Int
	get() = toInt()
val Long.long: Long
	get() = toLong()
val Long.float: Float
	get() = toFloat()
val Long.double: Double
	get() = toDouble()
val Long.string: String
	get() = toString()
val Float.byte: Byte
	get() = toByte()
val Float.short: Short
	get() = toShort()
val Float.int: Int
	get() = toInt()
val Float.long: Long
	get() = toLong()
val Float.float: Float
	get() = toFloat()
val Float.double: Double
	get() = toDouble()
val Float.string: String
	get() = toString()
val Double.byte: Byte
	get() = toByte()
val Double.short: Short
	get() = toShort()
val Double.int: Int
	get() = toInt()
val Double.long: Long
	get() = toLong()
val Double.float: Float
	get() = toFloat()
val Double.double: Double
	get() = toDouble()
val Double.string: String
	get() = toString()